// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeDisk(arg1:string):Promise<string>;

export function GetStatus():Promise<string>;

export function RunAction(arg1:string):Promise<string>;
