// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeDisk(arg1) {
  return window['go']['main']['App']['AnalyzeDisk'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function RunAction(arg1) {
  return window['go']['main']['App']['RunAction'](arg1);
}
